<a href="https://colab.research.google.com/github/VinuthaGovindappa/PythonInColaboratory/blob/master/Python_Day2_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# For Loops 

rad_angles = []

for a in [30, 60, 90]:
#   Calculate radian with given degree
  rad_angles = a * (22 / 7 / 180)
  print(rad_angles)
  
#   rad_angles.append(r)

0.5238095238095238
1.0476190476190477
1.5714285714285714


In [24]:
# print Qudrant 2 degree's

# q2_angles = []
# for a in [30, 60, 90, 120, 180]:
#   #   Calculate radian with given degree
#   q2_angles = a * (22 / 7 / 180)
#   print(q2_angles)
  
q2_angles = [] 

for a in [30, 60, 90, 120, 180]:
  if((a>=90) & (a<180)):
    q2_angles.append(a)
    
print(q2_angles)
    

IndentationError: ignored

Numpy


In [25]:
# numpy array

import numpy as np

# one D array
# 2 D array
# Zero matrix
# crate identical matrix

a = np.array([1, 2, 3])  
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
c = np.zeros((3, 4))
d = np.eye(3)

print(a)
print(b)
print(c)
print(d)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
# Basic inspecting operations

# shape, len, ndim, size, dtype

print(b.shape)
print(len(a))
print(b.ndim)
print(b.size)
print(b.dtype)

b = b.astype(int)
b.dtype



(2, 3)
3
2
6
int64


dtype('int64')

In [45]:
# Student Activity

from sklearn import datasets
iris = datasets.load_iris()

x = iris.data

# print(x)

# 1. print shape and dimension of this array x

print(x.shape)

# print(x)

# 2. Sub-array with only petal data and measurements from (100 to 140 rows)
print(x[100:140, 2:4 ])

# 3. assign Sub-array to Xsub and print cellblock

Xsub = x[100:140, 2:4]

print(Xsub)

# 4. print explcitly shape of Xsub

print(Xsub.shape)




(150, 4)
[[6.  2.5]
 [5.1 1.9]
 [5.9 2.1]
 [5.6 1.8]
 [5.8 2.2]
 [6.6 2.1]
 [4.5 1.7]
 [6.3 1.8]
 [5.8 1.8]
 [6.1 2.5]
 [5.1 2. ]
 [5.3 1.9]
 [5.5 2.1]
 [5.  2. ]
 [5.1 2.4]
 [5.3 2.3]
 [5.5 1.8]
 [6.7 2.2]
 [6.9 2.3]
 [5.  1.5]
 [5.7 2.3]
 [4.9 2. ]
 [6.7 2. ]
 [4.9 1.8]
 [5.7 2.1]
 [6.  1.8]
 [4.8 1.8]
 [4.9 1.8]
 [5.6 2.1]
 [5.8 1.6]
 [6.1 1.9]
 [6.4 2. ]
 [5.6 2.2]
 [5.1 1.5]
 [5.6 1.4]
 [6.1 2.3]
 [5.6 2.4]
 [5.5 1.8]
 [4.8 1.8]
 [5.4 2.1]]
[[6.  2.5]
 [5.1 1.9]
 [5.9 2.1]
 [5.6 1.8]
 [5.8 2.2]
 [6.6 2.1]
 [4.5 1.7]
 [6.3 1.8]
 [5.8 1.8]
 [6.1 2.5]
 [5.1 2. ]
 [5.3 1.9]
 [5.5 2.1]
 [5.  2. ]
 [5.1 2.4]
 [5.3 2.3]
 [5.5 1.8]
 [6.7 2.2]
 [6.9 2.3]
 [5.  1.5]
 [5.7 2.3]
 [4.9 2. ]
 [6.7 2. ]
 [4.9 1.8]
 [5.7 2.1]
 [6.  1.8]
 [4.8 1.8]
 [4.9 1.8]
 [5.6 2.1]
 [5.8 1.6]
 [6.1 1.9]
 [6.4 2. ]
 [5.6 2.2]
 [5.1 1.5]
 [5.6 1.4]
 [6.1 2.3]
 [5.6 2.4]
 [5.5 1.8]
 [4.8 1.8]
 [5.4 2.1]]
(40, 2)


In [51]:

# Upload file to colab 
# 
from google.colab import files
uploaded = files.upload()



Saving matches.csv to matches.csv


In [69]:
# Pandas DataFrame
# help tabular data "Python data analysis Library"

# read data from matches.csv from data folder
#

import pandas as pd

df = pd.read_csv('matches.csv')

print(df.shape)
print(df.columns)
print(list(df.index)[:10])
df.head()
df.head(2)
df.tail(3)

(577, 18)
Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


id  season       city        date                team1  \
574  575    2016      Delhi  2016-05-25  Sunrisers Hyderabad   
575  576    2016      Delhi  2016-05-27        Gujarat Lions   
576  577    2016  Bangalore  2016-05-29  Sunrisers Hyderabad   

                           team2            toss_winner toss_decision  result  \
574        Kolkata Knight Riders  Kolkata Knight Riders         field  normal   
575          Sunrisers Hyderabad    Sunrisers Hyderabad         field  normal   
576  Royal Challengers Bangalore    Sunrisers Hyderabad           bat  normal   

     dl_applied               winner  win_by_runs  win_by_wickets  \
574           0  Sunrisers Hyderabad           22               0   
575           0  Sunrisers Hyderabad            0               4   
576           0  Sunrisers Hyderabad            8               0   

    player_of_match                  venue          umpire1        umpire2  \
574    MC Henriques       Feroz Shah Kotla        M Erasmus  C Shamshuddin   
575       DA Warner       Feroz Shah Kotla        M Erasmus      CK Nandan   
576     BCJ Cutting  M Chinnaswamy Stadium  HDPK Dharmasena   BNJ Oxenford   

     umpire3  
574      NaN  
575      NaN  
576      NaN

In [83]:
# Subsetting DataFrames

# Only Bangalore games
# Subset data frame where city is bangalore

df[df['city']=='Bangalore']

# on above subset get only winners
df[df['city']=='Bangalore']['winner']

# use isin function to subset season is 2008,2015
df[df['season'].isin([2008,2015])]

# get only season and toss_winner from above subset
df[df['season'].isin([2008,2015])][['season','toss_winner']]

# use valuse_counts for winners

df['winner'].value_counts()

# use isnull().sum() get total of NAs

df['winner'].isnull().sum()


3

In [103]:
# index, ix, loc, iloc
# ix id depricated 

df.reset_index(inplace=True)
df.set_index('season',inplace=True)

df.iloc[0:10]
df.loc['2008']

date  level_0  index  id        city  \
season                                               
2008    2008-04-18        0      0   1   Bangalore   
2008    2008-04-19        1      1   2  Chandigarh   
2008    2008-04-19        2      2   3       Delhi   
2008    2008-04-20        3      3   4      Mumbai   
2008    2008-04-20        4      4   5     Kolkata   
2008    2008-04-21        5      5   6      Jaipur   
2008    2008-04-22        6      6   7   Hyderabad   
2008    2008-04-23        7      7   8     Chennai   
2008    2008-04-24        8      8   9   Hyderabad   
2008    2008-04-25        9      9  10  Chandigarh   
2008    2008-04-26       10     10  11   Bangalore   
2008    2008-04-26       11     11  12     Chennai   
2008    2008-04-27       12     12  13      Mumbai   
2008    2008-04-27       13     13  14  Chandigarh   
2008    2008-04-28       14     14  15   Bangalore   
2008    2008-04-29       15     15  16     Kolkata   
2008    2008-04-30       16     16  17       Delhi   
2008    2008-05-01       17     17  18   Hyderabad   
2008    2008-05-01       18     18  19      Jaipur   
2008    2008-05-02       19     19  20     Chennai   
2008    2008-05-25       20     20  21   Hyderabad   
2008    2008-05-03       21     21  22  Chandigarh   
2008    2008-05-04       22     22  23      Mumbai   
2008    2008-05-04       23     23  24      Jaipur   
2008    2008-05-05       24     24  25   Bangalore   
2008    2008-05-06       25     25  26     Chennai   
2008    2008-05-07       26     26  27      Mumbai   
2008    2008-05-08       27     27  28       Delhi   
2008    2008-05-08       28     28  29     Kolkata   
2008    2008-05-09       29     29  30      Jaipur   
2008    2008-05-28       30     30  31   Bangalore   
2008    2008-05-10       31     31  32     Chennai   
2008    2008-05-11       32     32  33   Hyderabad   
2008    2008-05-11       33     33  34      Jaipur   
2008    2008-05-12       34     34  35  Chandigarh   
2008    2008-05-13       35     35  36     Kolkata   
2008    2008-05-14       36     36  37      Mumbai   
2008    2008-05-28       37     37  38  Chandigarh   
2008    2008-05-15       38     38  39       Delhi   
2008    2008-05-16       39     39  40      Mumbai   
2008    2008-05-17       40     40  41       Delhi   
2008    2008-05-17       41     41  42      Jaipur   
2008    2008-05-18       42     42  43   Hyderabad   
2008    2008-05-18       43     43  44     Kolkata   
2008    2008-05-19       44     44  45   Bangalore   
2008    2008-05-20       45     45  46     Kolkata   
2008    2008-05-21       46     46  47      Mumbai   
2008    2008-05-21       47     47  48     Chennai   
2008    2008-05-23       48     48  49  Chandigarh   
2008    2008-05-24       49     49  50       Delhi   
2008    2008-05-24       50     50  51     Chennai   
2008    2008-05-03       51     51  52   Bangalore   
2008    2008-05-25       52     52  53     Kolkata   
2008    2008-05-26       53     53  54      Jaipur   
2008    2008-05-27       54     54  55   Hyderabad   
2008    2008-05-30       55     55  56      Mumbai   
2008    2008-05-31       56     56  57      Mumbai   
2008    2008-06-01       57     57  58      Mumbai   

                              team1                        team2  \
season                                                             
2008          Kolkata Knight Riders  Royal Challengers Bangalore   
2008            Chennai Super Kings              Kings XI Punjab   
2008               Rajasthan Royals             Delhi Daredevils   
2008                 Mumbai Indians  Royal Challengers Bangalore   
2008                Deccan Chargers        Kolkata Knight Riders   
2008                Kings XI Punjab             Rajasthan Royals   
2008                Deccan Chargers             Delhi Daredevils   
2008            Chennai Super Kings               Mumbai Indians   
2008                Deccan Chargers             Rajasthan Royals   
2008                Kings

In [104]:
# fillna attribute

df['winner'].fillna('bfill', inplace=True)
df.isnull().sum()

date                 0
level_0              0
index                0
id                   0
city                 7
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               0
win_by_runs          0
win_by_wickets       0
player_of_match      3
venue                0
umpire1              0
umpire2              0
umpire3            577
dtype: int64